dist: trusty
sudo: true

os:
  - linux

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache

language: python

python:
  - 3.5

env:
  matrix:
    - TOXENV=sanity
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=nightly WITH_YARN=true
    - TOXENV=nightly
    # Meta
    - TOXENV=flake8
    - TOXENV=manifest

before_install:
  - pip install codecov
  - GIT_LFS_VERSION=1.5.4
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      mkdir -p $HOME/bin
      wget https://github.com/github/git-lfs/releases/download/v$GIT_LFS_VERSION/git-lfs-linux-amd64-$GIT_LFS_VERSION.tar.gz
      tar xvfz git-lfs-linux-amd64-$GIT_LFS_VERSION.tar.gz
      mv git-lfs-$GIT_LFS_VERSION/git-lfs $HOME/bin/git-lfs
      export PATH=$PATH:$HOME/bin/
    fi
  - |
    if [[ $WITH_YARN == 'yes' ]]; then
      # Repo for newer Node.js versions
      curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      # Repo for Yarn
      sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
      echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      sudo apt-get update -qq
      sudo apt-get install -y -qq yarn
    fi

install:
  - pip install tox

before_script:
  - git lfs version
  - git lfs pull

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
