dist: trusty
sudo: false

os:
  - linux

cache:
  directories:
    - $HOME/.cache/pip

language: python

python:
  - 3.5

env:
  matrix:
    - TOXENV=sanity
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=nightly
    # Meta
    - TOXENV=flake8
    - TOXENV=manifest

before_install:
  - pip install codecov
  - GIT_LFS_VERSION=1.5.4
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v$GIT_LFS_VERSION/git-lfs-linux-amd64-$GIT_LFS_VERSION.tar.gz
  - tar xvfz git-lfs-linux-amd64-$GIT_LFS_VERSION.tar.gz
  - mv git-lfs-$GIT_LFS_VERSION/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/

install:
  - pip install tox

before_script:
  - git lfs version
  - git lfs pull

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
